# We use postgresql

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: development
  host: localhost
  pool: 5
  username: developer
  password: dev

test:
  <<: *default
  database: test
  host: localhost
  pool: 5
  username: developer
  password: dev

# The following setting are for use on MacOS
  #database: test_dev
  #username: YOUR_USERNAME
  #password:

production:
  <<: *default
  database: master #Database name
