# We use postgresql

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: grchombo_dev
  host: localhost
  pool: 5
  username: grchombo
  password: grchombo

test:
  <<: *default
  database: grchombo_test
  host: localhost
  pool: 5
  username: grchombo
  password: grchombo

# The following setting are for use on MacOS
  #database: test_dev
  #username: YOUR_USERNAME
  #password:

production:
  <<: *default
  database: master #Database name
